version: '3'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: "redis:6-alpine"

  backend:
    stdin_open: true
    tty: true
    container_name: "backend"
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  celery-beat:
    build: ./backend
    command: celery -A restaurant_website worker -l info -B
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

volumes:
  postgres_data:
