# Generated by Django 3.0.4 on 2020-05-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
