name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare project
        run: |
          cp .env.template .env
          docker-compose up -d
      - name: Run tests
        run: docker-compose exec -T backend coverage run --source='.' manage.py test
      - name: Run flake8
        run: docker-compose exec -T backend flake8
      - name: Run Mypy
        run: docker-compose exec -T backend mypy .
      - name: Cleaning
        run: docker-compose down -v
