name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare project
        run: |
          cp .env.template .env
          docker-compose run -d
      - name: Run tests
        run: |
          docker-compose exec backend coverage run --source='.' manage.py test
          docker-compose exec backend coverage report
      - name: Run flake8
        run: docker-compose exec backend flake8
      - name: Run flake8
        run: docker-compose exec backend mypy .
      - name: Cleaning
        run: |
          docker-compose down -v
